import { index, integer, real, sqliteTable, text, uniqueIndex } from "drizzle-orm/sqlite-core";

export const forecastJournal = sqliteTable("forecast_journal", {
  id: text("id").primaryKey(),
  modelVersion: text("model_version").notNull(),
  symbol: text("symbol").notNull(),
  market: text("market").notNull(),
  timeframe: text("timeframe").notNull(),
  asofTime: integer("asof_time").notNull(),
  dueTime: integer("due_time").notNull(),
  status: text("status").notNull().default("PENDING"),
  primaryDirection: text("primary_direction").notNull(),
  primaryWeight: real("primary_weight").notNull(),
  bullWeight: real("bull_weight").notNull(),
  sidewaysWeight: real("sideways_weight").notNull(),
  bearWeight: real("bear_weight").notNull(),
  currentPrice: real("current_price").notNull(),
  targetPrice: real("target_price").notNull(),
  invalidationPrice: real("invalidation_price").notNull(),
  horizonBars: integer("horizon_bars").notNull(),
  biasScore: integer("bias_score").notNull(),
  atr: real("atr").notNull(),
  historicalSamples: integer("historical_samples").notNull(),
  similarOutcomeRate: real("similar_outcome_rate"),
  driversJson: text("drivers_json").notNull(),
  featuresJson: text("features_json").notNull(),
  forecastJson: text("forecast_json").notNull(),
  createdAt: text("created_at").notNull(),
  evaluatedAt: integer("evaluated_at"),
  evaluationTime: integer("evaluation_time"),
  actualClose: real("actual_close"),
  actualDirection: text("actual_direction"),
  actualReturnPct: real("actual_return_pct"),
  correct: integer("correct", { mode: "boolean" }),
  targetHit: integer("target_hit", { mode: "boolean" }),
  invalidationHit: integer("invalidation_hit", { mode: "boolean" }),
  firstTouch: text("first_touch"),
  maxUpPct: real("max_up_pct"),
  maxDownPct: real("max_down_pct"),
  targetErrorPct: real("target_error_pct"),
}, (table) => [
  uniqueIndex("idx_forecast_unique").on(table.modelVersion, table.symbol, table.timeframe, table.asofTime),
  index("idx_forecast_pending_due").on(table.status, table.dueTime),
  index("idx_forecast_symbol_timeframe").on(table.symbol, table.timeframe, table.asofTime),
]);

export const marketNews = sqliteTable("market_news", {
  id: text("id").primaryKey(),
  symbol: text("symbol").notNull(),
  market: text("market").notNull(),
  publishedAt: integer("published_at").notNull(),
  title: text("title").notNull(),
  summary: text("summary").notNull(),
  url: text("url").notNull(),
  source: text("source").notNull(),
  category: text("category").notNull(),
  sentiment: text("sentiment").notNull(),
  sentimentScore: real("sentiment_score").notNull(),
  relevanceScore: real("relevance_score").notNull(),
  importance: text("importance").notNull(),
  topicsJson: text("topics_json").notNull(),
  provider: text("provider").notNull(),
  fetchedAt: integer("fetched_at").notNull(),
}, (table) => [
  uniqueIndex("idx_market_news_symbol_url").on(table.symbol, table.url),
  index("idx_market_news_symbol_published").on(table.symbol, table.publishedAt),
  index("idx_market_news_fetched").on(table.symbol, table.fetchedAt),
]);

export const paperAccounts = sqliteTable("paper_accounts", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  initialBalance: real("initial_balance").notNull(),
  balance: real("balance").notNull(),
  riskPerTradePct: real("risk_per_trade_pct").notNull(),
  feeBps: real("fee_bps").notNull(),
  slippageBps: real("slippage_bps").notNull(),
  maxOpenPositions: integer("max_open_positions").notNull(),
  enabled: integer("enabled", { mode: "boolean" }).notNull().default(true),
  entryMode: text("entry_mode").notNull().default("MANUAL"),
  rubPerUsdt: real("rub_per_usdt").notNull().default(80),
  createdAt: integer("created_at").notNull(),
  updatedAt: integer("updated_at").notNull(),
});

export const paperTrades = sqliteTable("paper_trades", {
  id: text("id").primaryKey(),
  accountId: text("account_id").notNull().references(() => paperAccounts.id),
  forecastId: text("forecast_id").notNull().references(() => forecastJournal.id),
  modelVersion: text("model_version").notNull(),
  symbol: text("symbol").notNull(),
  market: text("market").notNull(),
  timeframe: text("timeframe").notNull(),
  side: text("side").notNull(),
  status: text("status").notNull(),
  entrySource: text("entry_source").notNull().default("AUTO"),
  quoteCurrency: text("quote_currency").notNull().default("USDT"),
  fxRate: real("fx_rate").notNull().default(1),
  signalTime: integer("signal_time").notNull(),
  dueTime: integer("due_time").notNull(),
  entryTime: integer("entry_time"),
  entryTimeSource: text("entry_time_source").notNull().default("TIMEFRAME_CANDLE"),
  firstEntryTime: integer("first_entry_time"),
  scaleInCount: integer("scale_in_count").notNull().default(0),
  exitTime: integer("exit_time"),
  exitTimeSource: text("exit_time_source"),
  entryPrice: real("entry_price"),
  targetPrice: real("target_price").notNull(),
  stopPrice: real("stop_price").notNull(),
  exitPrice: real("exit_price"),
  quantity: real("quantity"),
  notional: real("notional"),
  riskAmount: real("risk_amount"),
  fees: real("fees").notNull().default(0),
  feesNative: real("fees_native").notNull().default(0),
  realizedPnl: real("realized_pnl"),
  realizedPnlNative: real("realized_pnl_native"),
  pnlPct: real("pnl_pct"),
  unrealizedPnl: real("unrealized_pnl"),
  unrealizedPnlNative: real("unrealized_pnl_native"),
  unrealizedPnlPct: real("unrealized_pnl_pct"),
  lastPrice: real("last_price"),
  maxFavorablePct: real("max_favorable_pct"),
  maxAdversePct: real("max_adverse_pct"),
  exitReason: text("exit_reason"),
  lastProcessedTime: integer("last_processed_time"),
  entryBlockReason: text("entry_block_reason"),
  entryBlockDetail: text("entry_block_detail"),
  entryBlockedAt: integer("entry_blocked_at"),
  createdAt: integer("created_at").notNull(),
  updatedAt: integer("updated_at").notNull(),
}, (table) => [
  uniqueIndex("idx_paper_trade_forecast").on(table.forecastId),
  index("idx_paper_trade_status_signal").on(table.status, table.signalTime),
  index("idx_paper_trade_symbol_timeframe").on(table.symbol, table.timeframe, table.signalTime),
]);

export const scalpingTrades = sqliteTable("scalping_trades", {
  id: text("id").primaryKey(),
  symbol: text("symbol").notNull(),
  side: text("side").notNull(),
  status: text("status").notNull(),
  entryPrice: real("entry_price").notNull(),
  quantity: real("quantity").notNull(),
  notional: real("notional").notNull(),
  stopPrice: real("stop_price").notNull(),
  targetPrice: real("target_price").notNull(),
  openedAt: integer("opened_at").notNull(),
  entryFee: real("entry_fee").notNull(),
  entryMode: text("entry_mode").notNull(),
  validity: text("validity").notNull().default("VALID"),
  invalidReason: text("invalid_reason"),
  signalKey: text("signal_key"),
  signalSnapshotJson: text("signal_snapshot_json"),
  closedAt: integer("closed_at"),
  exitPrice: real("exit_price"),
  pnl: real("pnl"),
  pnlPct: real("pnl_pct"),
  fees: real("fees"),
  exitReason: text("exit_reason"),
  createdAt: integer("created_at").notNull(),
  updatedAt: integer("updated_at").notNull(),
}, (table) => [
  index("idx_scalping_status_opened").on(table.status, table.openedAt),
  index("idx_scalping_symbol_opened").on(table.symbol, table.openedAt),
  index("idx_scalping_validity_closed").on(table.validity, table.closedAt),
]);
